<?php
/**
 * @file
 * Code for the suitcase_config feature.
 */

include_once 'suitcase_config.features.inc';

// Defining color constants.
define('SUITCASE_CONFIG_MAIN_BACKGROUND', 0);
define('SUITCASE_CONFIG_FOOTER_BACKGROUND', 1);
define('SUITCASE_CONFIG_FOOTER_TEXT', 2);
define('SUITCASE_CONFIG_HEADER_TEXT', 3);
define('SUITCASE_CONFIG_SITE_TEXT', 4);
define('SUITCASE_CONFIG_PRIMARY', 5);
define('SUITCASE_CONFIG_SECONDARY', 6);

/**
 * Implements hook_update_projects_alter().
 */
function suitcase_config_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['suitcase_config']);
}

// Disable blocks when the suitcase_config feature is enabled.
// This is actually called twice, once for each component in
// suitcase_config.info features (ctools and features_api).
function suitcase_config_pre_features_enable_feature($component) {
  // This conditional has nothing to do with ctools; it just ensures that
  // blocks are disabled only once.
  if ($component == 'ctools') {
    db_update('block')->fields(array('region' => '-1', 'status' => '0', ))->condition('delta', 'help')->condition('theme', 'suitcase')->execute();
    db_update('block')->fields(array('region' => '-1', 'status' => '0', ))->condition('delta', 'navigation')->condition('theme', 'suitcase')->execute();
    db_update('block')->fields(array('region' => '-1', 'status' => '0', ))->condition('delta', 'management')->condition('theme', 'suitcase')->execute();
    db_update('block')->fields(array('region' => '-1', 'status' => '0', ))->condition('delta', 'login')->condition('theme', 'suitcase')->execute();
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * @param $form
 * @param $form_state
 */
function suitcase_config_form_system_site_information_settings_alter(&$form, &$form_state) {
  $form['site_information']['site_slogan']['#title'] = 'Department name';
  $form['site_information']['site_slogan']['#weight'] = '1';
  $form['site_information']['dept_url']= array(
    '#type' => 'textfield',
    '#title' => 'Department URL',
    '#default_value' => '',
    '#description' => 'Full URL to the Department site',
    '#default_value' => variable_get('dept_url', $default = NULL),
    '#weight' => '2',
  );
  $form['#submit'][]= 'suitcase_config_form_system_information_submit';
}

function suitcase_config_form_system_information_submit($form, &$form_state) {
  variable_set('dept_url', $form_state['values']['dept_url']);
}

/**
 * Implements hook_menu().
 */
function suitcase_config_menu() {

  $items['admin/config/theme_settings'] = array(
    'title' => 'Theme',
    'description' => 'Settings related to formatting and configuring themes.',
    'position' => 'right',
    'weight' => -15,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/theme_settings/suitcase_config'] = array(
    'title' => 'Suitcase Settings',
    'description' => 'Custom CSS and site symbol configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('suitcase_config_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

/**
 * Implements hook_preprocess_HOOK
 */
function suitcase_config_preprocess_html(&$variables) {
  if ($GLOBALS['theme'] == 'suitcase') {
    drupal_add_css('public://suitcase_config/style.css', array('group' => 200));
  }
}

function suitcase_config_form($form, &$form_state) {
  $logo_default = variable_get('suitcase_config_logo', array('id' => NULL, 'uri' => NULL));
  $form['logo'] = array(
    '#type' => 'managed_file',
    '#name' => 'suitcase_config_logo',
    '#title' => t('Symbol Image File'),
    '#size' => 40,
    '#description' => t('Symbol should be  a .gif, .jpg, .jpeg, .png or .svg'),
    '#upload_location' => 'public://suitcase_config',
    '#upload_validators' => array('file_validate_extensions' => array('png gif jpg jpeg svg')),
    '#default_value' => $logo_default['id'],
  );

  $form['colors'] = array(
    '#type' => 'fieldset',
    '#title' => t('Colors'),
    '#description' => t('For standard Iowa State University sites complying with the Visual Identity System these colors should be set to their default values.'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['colors']['suitcase_config_main_background_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Main Background Color'),
    '#description' => t('Default: #f4f3e8'),
    '#default_value' => variable_get('suitcase_config_main_background_color', '#f4f3e8'),
  );

  $form['colors']['suitcase_config_footer_background_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Footer Background Color'),
    '#description' => t('Default: #CEC9BB'),
    '#default_value' => variable_get('suitcase_config_footer_background_color', '#CEC9BB'),
  );

  $form['colors']['suitcase_config_footer_text_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Footer Text Color'),
    '#description' => t('Default: #ffffff'),
    '#default_value' => variable_get('suitcase_config_footer_text_color', '#ffffff'),
  );

  $form['colors']['suitcase_config_header_text_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Header Text Color'),
    '#description' => t('Default: #fff'),
    '#default_value' => variable_get('suitcase_config_header_text_color', '#fff'),
  );

  $form['colors']['suitcase_config_site_text_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Site Text Color'),
    '#description' => t('Default: #333'),
    '#default_value' => variable_get('suitcase_config_site_text_color', '#333'),
  );

  $form['colors']['suitcase_config_primary_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Primary Color'),
    '#description' => t('Default: #CB1A2A'),
    '#default_value' => variable_get('suitcase_config_primary_color', '#CB1A2A'),
  );

  $form['colors']['suitcase_config_secondary_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Secondary Color'),
    '#description' => t('Default: #DFBD00'),
    '#default_value' => variable_get('suitcase_config_secondary_color', '#DFBD00'),
  );

  $form['layout'] = array(
    '#type' => 'fieldset',
    '#title' => t('Layout'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t('Find department name and URL settings in <a href="@siteinfo">Site Information</a>.', array('@siteinfo' => url('admin/config/system/site-information'))),
  );

  $form['layout']['suitcase_config_blackbar_display'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show black bar'),
    '#description' => t('The black bar contains the Iowa State University links to CyMail, Outlook, Blackboard, AccessPlus, the Directory, Maps, ISU Contact Us, and the index.'),
    '#default_value' => variable_get('suitcase_config_blackbar_display', 1),
  );

  $form['layout']['suitcase_config_isu_nameplate_display'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show ISU nameplate'),
    '#description' => t('The ISU nameplate identifies Iowa State University above the site name and department title.'),
    '#default_value' => variable_get('suitcase_config_isu_nameplate_display', 1),
  );

  $form['#submit'][] = 'suitcase_config_form_submit';
  $form['#validate'][] = 'suitcase_config_form_validate';

  return system_settings_form($form);
}

function suitcase_config_form_submit($form, &$form_state) {

  // Process logo if the logo is defined in the form.
  if ($form_state['values']['logo']) {
    $file = file_load($form_state['values']['logo']);
    if ($file->status != FILE_STATUS_PERMANENT) {
      // If the image isn't already managed, delete the old, manage it and set our variable.

      // Delete the old logo file if it was defined in our variable.
      $old_logo = variable_get('suitcase_config_logo');
      if ($old_logo) {
        $old_logo_file = file_load($old_logo['id']);
        file_usage_delete($old_logo_file, 'suitcase_config', 'logo');
        file_delete($old_logo_file);
      }

      // Manage the new logo file.
      $file->status = FILE_STATUS_PERMANENT;
      file_save($file);
      file_usage_add($file, 'suitcase_config', 'logo', $file->fid);

      // Set the new logo variable.
      $new_logo = array(
        'id' => $file->fid,
        'uri' => $file->uri,
      );
      variable_set('suitcase_config_logo', $new_logo);
    }
  }
  else {
    // If the logo is not defined or has been removed in the form, delete it.
    $suitcase_config_logo = variable_get('suitcase_config_logo');
    if ($suitcase_config_logo) {
      // If the logo was set in configuration, delete it.
      $file = file_load($suitcase_config_logo['id']);
      file_usage_delete($file, 'suitcase_config', 'logo');
      file_delete($file);
      variable_del('suitcase_config_logo');
    }
  }

  // Process CSS.
  $css = _suitcase_config_set_color(SUITCASE_CONFIG_MAIN_BACKGROUND, $form_state['values']['suitcase_config_main_background_color']);
  $css .= _suitcase_config_set_color(SUITCASE_CONFIG_FOOTER_BACKGROUND, $form_state['values']['suitcase_config_footer_background_color']);
  $css .= _suitcase_config_set_color(SUITCASE_CONFIG_FOOTER_TEXT, $form_state['values']['suitcase_config_footer_text_color']);
  $css .= _suitcase_config_set_color(SUITCASE_CONFIG_HEADER_TEXT, $form_state['values']['suitcase_config_header_text_color']);
  $css .= _suitcase_config_set_color(SUITCASE_CONFIG_SITE_TEXT, $form_state['values']['suitcase_config_site_text_color']);
  $css .= _suitcase_config_set_color(SUITCASE_CONFIG_PRIMARY, $form_state['values']['suitcase_config_primary_color']);
  $css .= _suitcase_config_set_color(SUITCASE_CONFIG_SECONDARY, $form_state['values']['suitcase_config_secondary_color']);
  // $css = suitcase_config_add_style(array('background-color' => $form_state['values']['suitcase_config_background_color']), '.section-content');
  // $css .= suitcase_config_add_style(array(
  //   'background-color' => $form_state['values']['suitcase_config_header_color'],
  //   'border-bottom' => '6px solid ' . $form_state['values']['suitcase_config_header_border_color'],
  // ), '.section-header');
  // $css .= suitcase_config_add_style(array('background-color' => $form_state['values']['suitcase_config_header_color']), '#zone-menu.sticky-top');
  // $css .= suitcase_config_add_style(array('background-color' => $form_state['values']['suitcase_config_footer_color']), 'body');
  // $css .= suitcase_config_add_style(array('color' => $form_state['values']['suitcase_config_primary_text_color']), '.section h1,a,a:link,a:visited');
  // $css .= suitcase_config_add_style(array('color' => $form_state['values']['suitcase_config_secondary_text_color']), '.site-name a:hover,.site-name-slogan a');

  // Write styles to, e.g., files/suitcase_config/style.css
  $dir = 'public://suitcase_config';
  file_prepare_directory($dir, FILE_CREATE_DIRECTORY);
  file_save_data($css, 'public://suitcase_config/style.css', FILE_EXISTS_REPLACE);
}

function suitcase_config_form_validate($form, &$form_state) {
  // Validate logo field uploads.
  $logo_validators = array('file_validate_extensions' => array('png gif jpg jpeg svg'));

  // Check for a new uploaded logo.
  $file = file_save_upload('logo', $logo_validators, FALSE, FILE_EXISTS_REPLACE);
  if (isset($file)) {
    // File upload was attempted.
    if ($file) {
      // Put the temporary file in form_values so we can save it on suitcase_config_form_submit().
      $form_state['values']['logo'] = $file->fid;
    }
    else {
      // File upload failed.
      form_set_error('logo', t('The symbol could not be uploaded'));
    }
  }

   // Validate CSS Fields.
   if (!suitcase_config_valid_css_color($form_state['values']['suitcase_config_main_background_color'])) {
     form_set_error('suitcase_config_main_background_color', t('Main Background Color is invalid.'));
   }
   if (!suitcase_config_valid_css_color($form_state['values']['suitcase_config_footer_background_color'])) {
     form_set_error('suitcase_config_footer_background_color', t('Footer Background Color color is invalid.'));
   }
   if (!suitcase_config_valid_css_color($form_state['values']['suitcase_config_footer_text_color'])) {
     form_set_error('suitcase_config_footer_text_color', t('Footer Text Color is invalid.'));
   }
   if (!suitcase_config_valid_css_color($form_state['values']['suitcase_config_header_text_color'])) {
     form_set_error('suitcase_config_header_text_color', t('Header Text Color is invalid.'));
   }
   if (!suitcase_config_valid_css_color($form_state['values']['suitcase_config_site_text_color'])) {
     form_set_error('suitcase_config_site_text_color', t('Site Text Color is invalid.'));
   }
   if (!suitcase_config_valid_css_color($form_state['values']['suitcase_config_primary_color'])) {
     form_set_error('suitcase_config_primary_color', t('Primary Color is invalid.'));
   }
  if (!suitcase_config_valid_css_color($form_state['values']['suitcase_config_secondary_color'])) {
    form_set_error('suitcase_config_secondary_color', t('Secondary Color is invalid.'));
  }
}

function suitcase_config_valid_css_color($color) {
  // Limit the allowed characters to the list in the pattern.
  $pattern = "/[^ abcdefghijklmnopqrstuvwxyz1234567890(),#%.]/im";
  return !preg_match($pattern, $color);
}

function _suitcase_config_add_style($styles, $selector) {
  $s = '';
  foreach ($styles as $key => $value) {
    $s .= $key . ':' . $value . ';';
  }
  return $selector . '{' . $s . "}\n";
}

function _suitcase_config_set_color($type, $color) {
  switch ($type) {
    case SUITCASE_CONFIG_MAIN_BACKGROUND:
      return _suitcase_config_add_style(array(
        'background-color' => $color
      ), '.section-content');
      break;
    case SUITCASE_CONFIG_FOOTER_BACKGROUND:
      return _suitcase_config_add_style(array(
        'background-color' => $color
      ), 'body');
      break;
    case SUITCASE_CONFIG_FOOTER_TEXT:
      return _suitcase_config_add_style(array(
        'color' => $color
      ), '#block-menu-menu-footer .leaf a, .zone-footer a, .zone-footer p, .zone-footer li, .zone-footer span, .zone-footer strong, .zone-footer em');
      break;
    case SUITCASE_CONFIG_HEADER_TEXT:
      return _suitcase_config_add_style(array(
        'color' => $color
      ), '.site-name-slogan>.site-name>a, .site-name-slogan>.site-slogan>a, nav.navigation .main-menu>li a, nav.navigation .secondary-menu>li a');
      break;
    case SUITCASE_CONFIG_SITE_TEXT:
      return _suitcase_config_add_style(array(
        'color' => $color
      ), 'a, p, li, span, strong, em');
      break;
    case SUITCASE_CONFIG_PRIMARY:
      $css = _suitcase_config_add_style(array(
        'color' => $color
      ), 'section h1, a, a:link, a:visited');
      return $css . _suitcase_config_add_style(array(
        'background-color' => $color
      ), '.section-header, #zone-menu.sticky-top');
      break;
    case SUITCASE_CONFIG_SECONDARY:
      $css = _suitcase_config_add_style(array(
        'border-bottom-color' => $color
      ), '.panel-pane > h2.pane-title, .zone-content aside .block .block-title, .zone-postscript .block h2.block-title, .section-header, .view-display-id-people_grid .view-content > h3');
      return $css . _suitcase_config_add_style(array(
        'border-color' => $color
      ), 'input[type=text]:focus, textarea:focus, .page-search .search-form input#edit-submit:hover, .page form#search-block-form .form-actions input.form-submit:hover');
      break;
    default:
      # code...
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Since suitcase_config is handling the Omega logo functions, remove those
 * from the theme settings form and point user to the Suitcase Settings page.
 */
function suitcase_config_form_system_theme_settings_alter(&$form) {
  // If settings for suitcase are being displayed.
  if (isset($form['suitcase'])) {
    $form['logo']['default_logo']['#access'] = FALSE;
    $form['logo']['settings']['logo_path']['#access'] = FALSE;
    $form['logo']['settings']['logo_upload']['#access'] = FALSE;
    $form['logo']['#description'] = t('With the Suitcase theme enabled, these settings are available at !Suitcase Settings.', array('!Suitcase Settings' => l(t('Suitcase Settings'), 'admin/config/theme_settings/suitcase_config')));
    $form['theme_settings']['toggle_logo']['#access'] = FALSE;
  }
}
